### ISSUE TITLE
Make path to source customizable

### ISSUE THREAD

**Issue by perseus-me** [idlesign/pycbrf#1]
CBRF can change url to banks or swift sources. E.g `http://www.cbr.ru/mcirabis/BIK -> http://www.cbr.ru/vfs/mcirabis/BIK`. It'll be useful to add possibility to change url.

**Comment by idlesign** [comment]
Sure, they can. Just as they can change db file names and field names.
At the same time the number of library users who are able and willing to customize URLs (or any other aspect on that matter) tends to be comparatively small. In some cases it' even simpler to file an issue.

Nevertheless I'm ready to accept a pull request addressing the issue.

**Comment by perseus-fyi** [comment]
> Sure, they can.

They did =). They changed url about a month ago and db file names (lower case to upper case) two days ago.

**Comment by idlesign** [comment]
Yeap, I'm aware of it, that's why the above said.
